// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxSUDJhU5EVcRTJ7dl7jU4uU_7JaBr4GA',
    appId: '1:413703789482:web:d294ce04a5b8213c8c69d3',
    messagingSenderId: '413703789482',
    projectId: 'study-app-f69bf',
    authDomain: 'study-app-f69bf.firebaseapp.com',
    storageBucket: 'study-app-f69bf.appspot.com',
    measurementId: 'G-0HRX8H2M8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz6h7YM6G8MQMagF6DUn5_di3_aXh3UVM',
    appId: '1:413703789482:android:58b122e53a9920df8c69d3',
    messagingSenderId: '413703789482',
    projectId: 'study-app-f69bf',
    storageBucket: 'study-app-f69bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeWiQ0MDKwrSsvrOZzZneg4biU1aMGD2M',
    appId: '1:413703789482:ios:e4af8e55946e6f968c69d3',
    messagingSenderId: '413703789482',
    projectId: 'study-app-f69bf',
    storageBucket: 'study-app-f69bf.appspot.com',
    iosClientId: '413703789482-a47kn6i9kal2chjp6b068av27l1iiu6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
